notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot

branches:
  only:
    - master

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
